### ISSUE TITLE
1.1.10 causes crash

### ISSUE THREAD

**Issue by dtrunk90** [linuxmint/blueberry#31]
Previous version 1.1.9 worked. New version 1.1.10 causes crash.

Terminal output:
```
$ blueberry
**
ERROR:lib/bluez/adapter.c:165:adapter_get_dbus_object_path: assertion failed: (ADAPTER_IS(self))
Traceback (most recent call last):
  File "/usr/lib/blueberry/blueberry.py", line 35, in on_activate
    self.create_window()
  File "/usr/lib/blueberry/blueberry.py", line 154, in create_window
    self.adapter_name_entry.set_text(self.get_default_adapter_name())
  File "/usr/lib/blueberry/blueberry.py", line 231, in get_default_adapter_name
    output = subprocess.check_output(["bt-adapter", "-i"]).strip()
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bt-adapter', '-i']' returned non-zero exit status -6
```

on Asus Zenbook Prime UX31A-R4003V

**Comment by asahaf** [comment]
Same crash happens on all machines I have. I downgraded the package to the previous version till the issue gets fixed.

**Comment by AuroraWright** [comment]
You need bt-adapter which is part of https://github.com/khvzak/bluez-tools/tree/master

**Comment by dtrunk90** [comment]
bt-adapter (bluez-tools) is installed

```
anny@danny:~$ blueberry
**
ERROR:lib/bluez/adapter.c:165:adapter_get_dbus_object_path: assertion failed: (ADAPTER_IS(self))
Traceback (most recent call last):
  File "/usr/lib/blueberry/blueberry.py", line 35, in on_activate
    self.create_window()
  File "/usr/lib/blueberry/blueberry.py", line 154, in create_window
    self.adapter_name_entry.set_text(self.get_default_adapter_name())
  File "/usr/lib/blueberry/blueberry.py", line 231, in get_default_adapter_name
    output = subprocess.check_output(["bt-adapter", "-i"]).strip()
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bt-adapter', '-i']' returned non-zero exit status -6
danny@danny:~$ bt-adapter
Usage:
  bt-adapter [OPTION...] - a bluetooth adapter manager

Version UNKNOWN

Help Options:
  -h, --help                   Show help options

Application Options:
  -l, --list                   List all available adapters
  -a, --adapter=<name|mac>     Adapter Name or MAC
  -i, --info                   Show adapter info
  -d, --discover               Discover remote devices
  -s, --set                    Set adapter property

Set Options:
  --set <property> <value>
  Where `property` is one of:
     Name
     Discoverable
     DiscoverableTimeout
     Pairable
     PairableTimeout
     Powered

Report bugs to <zxteam@gmail.com>.Project home page <http://code.google.com/p/bluez-tools/>.
```

**Comment by dtrunk90** [comment]
I noticed the missing light on my keyboard which shows the wifi state. Wifi actually worked. So I pressed Fn+F2 two times to disable and enable again. After the light was on blueberry started without problems. Turning off bluetooth again through blueberry results in the same error again. So, this could be still a blueberry bug.

**Comment by Irvinehimself** [comment]
Same problem on Toshiba Satelite running Arch Linux with Xfce desktop

After a lot of gtk parsing errors:

```
(blueberry.py:1105): Gtk-WARNING **: Theme parsing error: gtk.css:63:28: The :prelight pseudo-class is deprecated. Use :hover instead.

*
*
*
(blueberry.py:1105): Gtk-WARNING **: Theme parsing error: <data>:1:41: The style property GtkWidget:wide-separators is deprecated and shouldn't be used anymore. It will be removed in a future version
**
ERROR:lib/bluez/adapter.c:165:adapter_get_dbus_object_path: assertion failed: (ADAPTER_IS(self))
Traceback (most recent call last):
  File "/usr/lib/blueberry/blueberry.py", line 35, in on_activate
    self.create_window()
  File "/usr/lib/blueberry/blueberry.py", line 154, in create_window
    self.adapter_name_entry.set_text(self.get_default_adapter_name())
  File "/usr/lib/blueberry/blueberry.py", line 231, in get_default_adapter_name
    output = subprocess.check_output(["bt-adapter", "-i"]).strip()
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bt-adapter', '-i']' returned non-zero exit status -6

```

**Comment by sherter** [comment]
Same problem here. As long as bluetooth is blocked, the device manager won't start.
After unblocking bluetooth (`rfkill unblock bluetooth`),  the device manager starts just fine when clicking on the tray icon.

**Comment by leigh123linux** [comment]
Can you lot reproduce the issue after running?

```
sudo systemctl start bluetooth.service
```

```
$ blueberry
Agent registration failed: Cannot invoke method; proxy is for a well-known name without an owner and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
Agent unregistration failed: Cannot invoke method; proxy is for a well-known name without an owner and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag 'g-io-error-quark'

(blueberry.py:20062): Gtk-WARNING **: Theme parsing error: <data>:1:41: The style property GtkWidget:wide-separators is deprecated and shouldn't be used anymore. It will be removed in a future version
**
ERROR:lib/helpers.c:319:intf_supported: assertion failed: (introspection_proxy != NULL)
Traceback (most recent call last):
  File "/usr/lib/blueberry/blueberry.py", line 35, in on_activate
    self.create_window()
  File "/usr/lib/blueberry/blueberry.py", line 154, in create_window
    self.adapter_name_entry.set_text(self.get_default_adapter_name())
  File "/usr/lib/blueberry/blueberry.py", line 231, in get_default_adapter_name
    output = subprocess.check_output(["bt-adapter", "-i"]).strip()
  File "/usr/lib64/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bt-adapter', '-i']' returned non-zero exit status -6

$ rfkill list
0: hci0: Bluetooth
	Soft blocked: no
	Hard blocked: no
1: phy0: Wireless LAN
	Soft blocked: no
	Hard blocked: no

$ bt-adapter -i
**
ERROR:lib/helpers.c:319:intf_supported: assertion failed: (introspection_proxy != NULL)
Aborted (core dumped)

$ sudo systemctl status bluetooth.service 
[sudo] password for leigh: 
● bluetooth.service - Bluetooth service
   Loaded: loaded (/usr/lib/systemd/system/bluetooth.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:bluetoothd(8)

sudo systemctl start bluetooth.service

$ bt-adapter -i
[hci0]
  Name: main_pc.leigh123linux
  Address: 7C:5C:F8:11:3C:52
  Alias: ChromeLinux_7807 [rw]
  Class: 0xc0104
  Discoverable: 0 [rw]
  DiscoverableTimeout: 0 [rw]
  Discovering: 0
  Pairable: 1 [rw]
  PairableTimeout: 0 [rw]
  Powered: 1 [rw]
  UUIDs: [HeadsetAudioGateway, 00001801-0000-1000-8000-00805f9b34fb, AVRemoteControl, 00001800-0000-1000-8000-00805f9b34fb, PnPInformation, AVRemoteControlTarget, AudioSink, AudioSource]
```

**Comment by mausworks** [comment]
@clefebvre had the same problem, forgot to start/enable `bluetooth.service` :man_facepalming: 

Thanks!
