### ISSUE TITLE
blueberry-tray fails to launch

### ISSUE THREAD

**Issue by biiiep** [linuxmint/blueberry#97]
Hey,
blueberry-tray doesn't start anymore since i upgraded from 1.2.9 to 1.3.4.

 I am using Arch Linux, the packages version:

```
Name            : blueberry
Version         : 1.3.4-1
Description     : Bluetooth configuration tool
Architecture    : any
URL             : https://github.com/linuxmint/blueberry
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : bluez-tools  gnome-bluetooth  python-dbus  python-gobject  python-setproctitle  rfkill
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 1743,01 KiB
Packager        : Balló György <ballogyor+arch@gmail.com>
Build Date      : Mi 08 Jan 2020 23:05:46 CET
Install Date    : Do 09 Jan 2020 20:07:05 CET
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

When i launch it aborts and throws the following error:

```
$ blueberry-tray 
Traceback (most recent call last):
  File "/usr/lib/blueberry/blueberry-tray.py", line 8, in <module>
    gi.require_version('XApp', '1.0')
  File "/usr/lib/python3.8/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace XApp not available
```

**Comment by leigh123linux** [comment]
This is an Arch packaging issue.

**Comment by luto** [comment]
(refer to https://bugs.archlinux.org/task/65119 for a solution.)
